/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as PrivacyPolicyImport } from "./routes/privacy-policy"
import { Route as IndexImport } from "./routes/index"
import { Route as UserIndexImport } from "./routes/user/index"
import { Route as SalesIndexImport } from "./routes/sales/index"
import { Route as PrivacyPolicyIndexImport } from "./routes/privacy-policy/index"
import { Route as PostauthIndexImport } from "./routes/postauth/index"
import { Route as MarketingStorageIndexImport } from "./routes/marketing-storage/index"
import { Route as LivestreamIndexImport } from "./routes/livestream/index"
import { Route as LandingIndexImport } from "./routes/landing/index"
import { Route as AccessDeniedIndexImport } from "./routes/access-denied/index"
import { Route as SalesTasksIndexImport } from "./routes/sales/tasks/index"
import { Route as SalesPriceIndexImport } from "./routes/sales/price/index"
import { Route as SalesOrdersIndexImport } from "./routes/sales/orders/index"
import { Route as SalesMessagesIndexImport } from "./routes/sales/messages/index"
import { Route as SalesItemsIndexImport } from "./routes/sales/items/index"
import { Route as SalesFunnelIndexImport } from "./routes/sales/funnel/index"
import { Route as SalesDashboardIndexImport } from "./routes/sales/dashboard/index"
import { Route as SalesDailyReportsIndexImport } from "./routes/sales/daily-reports/index"
import { Route as SalesCustomerRanksIndexImport } from "./routes/sales/customer-ranks/index"
import { Route as SalesChannelsIndexImport } from "./routes/sales/channels/index"
import { Route as MarketingStorageTasksIndexImport } from "./routes/marketing-storage/tasks/index"
import { Route as MarketingStorageSystemLogsIndexImport } from "./routes/marketing-storage/system-logs/index"
import { Route as MarketingStorageStorageIndexImport } from "./routes/marketing-storage/storage/index"
import { Route as MarketingStorageOrdersLogsIndexImport } from "./routes/marketing-storage/orders-logs/index"
import { Route as MarketingStorageOldLogsIndexImport } from "./routes/marketing-storage/old-logs/index"
import { Route as MarketingStorageLogsIndexImport } from "./routes/marketing-storage/logs/index"
import { Route as MarketingStorageIncomesIndexImport } from "./routes/marketing-storage/incomes/index"
import { Route as MarketingStorageDeliveredRequestsIndexImport } from "./routes/marketing-storage/delivered-requests/index"
import { Route as MarketingStorageCalfileIndexImport } from "./routes/marketing-storage/calfile/index"
import { Route as MarketingStorageCalIndexImport } from "./routes/marketing-storage/cal/index"
import { Route as MarketingStorageAccountingStorageIndexImport } from "./routes/marketing-storage/accounting-storage/index"
import { Route as LivestreamStatsIndexImport } from "./routes/livestream/stats/index"
import { Route as LivestreamPeriodsIndexImport } from "./routes/livestream/periods/index"
import { Route as LivestreamMembersIndexImport } from "./routes/livestream/members/index"
import { Route as LivestreamGoalsIndexImport } from "./routes/livestream/goals/index"
import { Route as LivestreamChannelsIndexImport } from "./routes/livestream/channels/index"
import { Route as LivestreamCalendarIndexImport } from "./routes/livestream/calendar/index"
import { Route as LandingLandingPageIndexImport } from "./routes/landing/landing-page/index"
import { Route as SalesOrdersOrderIdImport } from "./routes/sales/orders/$orderId"
import { Route as SalesMessagesConversationIdImport } from "./routes/sales/messages/$conversationId"
import { Route as SalesItemsItemIdImport } from "./routes/sales/items/$itemId"
import { Route as SalesFunnelFunnelIdImport } from "./routes/sales/funnel/$funnelId"
import { Route as SalesDashboardKpiIdImport } from "./routes/sales/dashboard/$kpiId"

// Create/Update Routes

const PrivacyPolicyRoute = PrivacyPolicyImport.update({
  id: "/privacy-policy",
  path: "/privacy-policy",
  getParentRoute: () => rootRoute
} as any)

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute
} as any)

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute
} as any)

const UserIndexRoute = UserIndexImport.update({
  id: "/user/",
  path: "/user/",
  getParentRoute: () => rootRoute
} as any)

const SalesIndexRoute = SalesIndexImport.update({
  id: "/sales/",
  path: "/sales/",
  getParentRoute: () => rootRoute
} as any)

const PrivacyPolicyIndexRoute = PrivacyPolicyIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PrivacyPolicyRoute
} as any)

const PostauthIndexRoute = PostauthIndexImport.update({
  id: "/postauth/",
  path: "/postauth/",
  getParentRoute: () => rootRoute
} as any)

const MarketingStorageIndexRoute = MarketingStorageIndexImport.update({
  id: "/marketing-storage/",
  path: "/marketing-storage/",
  getParentRoute: () => rootRoute
} as any)

const LivestreamIndexRoute = LivestreamIndexImport.update({
  id: "/livestream/",
  path: "/livestream/",
  getParentRoute: () => rootRoute
} as any)

const LandingIndexRoute = LandingIndexImport.update({
  id: "/landing/",
  path: "/landing/",
  getParentRoute: () => rootRoute
} as any)

const AccessDeniedIndexRoute = AccessDeniedIndexImport.update({
  id: "/access-denied/",
  path: "/access-denied/",
  getParentRoute: () => rootRoute
} as any)

const SalesTasksIndexRoute = SalesTasksIndexImport.update({
  id: "/sales/tasks/",
  path: "/sales/tasks/",
  getParentRoute: () => rootRoute
} as any)

const SalesPriceIndexRoute = SalesPriceIndexImport.update({
  id: "/sales/price/",
  path: "/sales/price/",
  getParentRoute: () => rootRoute
} as any)

const SalesOrdersIndexRoute = SalesOrdersIndexImport.update({
  id: "/sales/orders/",
  path: "/sales/orders/",
  getParentRoute: () => rootRoute
} as any)

const SalesMessagesIndexRoute = SalesMessagesIndexImport.update({
  id: "/sales/messages/",
  path: "/sales/messages/",
  getParentRoute: () => rootRoute
} as any)

const SalesItemsIndexRoute = SalesItemsIndexImport.update({
  id: "/sales/items/",
  path: "/sales/items/",
  getParentRoute: () => rootRoute
} as any)

const SalesFunnelIndexRoute = SalesFunnelIndexImport.update({
  id: "/sales/funnel/",
  path: "/sales/funnel/",
  getParentRoute: () => rootRoute
} as any)

const SalesDashboardIndexRoute = SalesDashboardIndexImport.update({
  id: "/sales/dashboard/",
  path: "/sales/dashboard/",
  getParentRoute: () => rootRoute
} as any)

const SalesDailyReportsIndexRoute = SalesDailyReportsIndexImport.update({
  id: "/sales/daily-reports/",
  path: "/sales/daily-reports/",
  getParentRoute: () => rootRoute
} as any)

const SalesCustomerRanksIndexRoute = SalesCustomerRanksIndexImport.update({
  id: "/sales/customer-ranks/",
  path: "/sales/customer-ranks/",
  getParentRoute: () => rootRoute
} as any)

const SalesChannelsIndexRoute = SalesChannelsIndexImport.update({
  id: "/sales/channels/",
  path: "/sales/channels/",
  getParentRoute: () => rootRoute
} as any)

const MarketingStorageTasksIndexRoute = MarketingStorageTasksIndexImport.update(
  {
    id: "/marketing-storage/tasks/",
    path: "/marketing-storage/tasks/",
    getParentRoute: () => rootRoute
  } as any
)

const MarketingStorageSystemLogsIndexRoute =
  MarketingStorageSystemLogsIndexImport.update({
    id: "/marketing-storage/system-logs/",
    path: "/marketing-storage/system-logs/",
    getParentRoute: () => rootRoute
  } as any)

const MarketingStorageStorageIndexRoute =
  MarketingStorageStorageIndexImport.update({
    id: "/marketing-storage/storage/",
    path: "/marketing-storage/storage/",
    getParentRoute: () => rootRoute
  } as any)

const MarketingStorageOrdersLogsIndexRoute =
  MarketingStorageOrdersLogsIndexImport.update({
    id: "/marketing-storage/orders-logs/",
    path: "/marketing-storage/orders-logs/",
    getParentRoute: () => rootRoute
  } as any)

const MarketingStorageOldLogsIndexRoute =
  MarketingStorageOldLogsIndexImport.update({
    id: "/marketing-storage/old-logs/",
    path: "/marketing-storage/old-logs/",
    getParentRoute: () => rootRoute
  } as any)

const MarketingStorageLogsIndexRoute = MarketingStorageLogsIndexImport.update({
  id: "/marketing-storage/logs/",
  path: "/marketing-storage/logs/",
  getParentRoute: () => rootRoute
} as any)

const MarketingStorageIncomesIndexRoute =
  MarketingStorageIncomesIndexImport.update({
    id: "/marketing-storage/incomes/",
    path: "/marketing-storage/incomes/",
    getParentRoute: () => rootRoute
  } as any)

const MarketingStorageDeliveredRequestsIndexRoute =
  MarketingStorageDeliveredRequestsIndexImport.update({
    id: "/marketing-storage/delivered-requests/",
    path: "/marketing-storage/delivered-requests/",
    getParentRoute: () => rootRoute
  } as any)

const MarketingStorageCalfileIndexRoute =
  MarketingStorageCalfileIndexImport.update({
    id: "/marketing-storage/calfile/",
    path: "/marketing-storage/calfile/",
    getParentRoute: () => rootRoute
  } as any)

const MarketingStorageCalIndexRoute = MarketingStorageCalIndexImport.update({
  id: "/marketing-storage/cal/",
  path: "/marketing-storage/cal/",
  getParentRoute: () => rootRoute
} as any)

const MarketingStorageAccountingStorageIndexRoute =
  MarketingStorageAccountingStorageIndexImport.update({
    id: "/marketing-storage/accounting-storage/",
    path: "/marketing-storage/accounting-storage/",
    getParentRoute: () => rootRoute
  } as any)

const LivestreamStatsIndexRoute = LivestreamStatsIndexImport.update({
  id: "/livestream/stats/",
  path: "/livestream/stats/",
  getParentRoute: () => rootRoute
} as any)

const LivestreamPeriodsIndexRoute = LivestreamPeriodsIndexImport.update({
  id: "/livestream/periods/",
  path: "/livestream/periods/",
  getParentRoute: () => rootRoute
} as any)

const LivestreamMembersIndexRoute = LivestreamMembersIndexImport.update({
  id: "/livestream/members/",
  path: "/livestream/members/",
  getParentRoute: () => rootRoute
} as any)

const LivestreamGoalsIndexRoute = LivestreamGoalsIndexImport.update({
  id: "/livestream/goals/",
  path: "/livestream/goals/",
  getParentRoute: () => rootRoute
} as any)

const LivestreamChannelsIndexRoute = LivestreamChannelsIndexImport.update({
  id: "/livestream/channels/",
  path: "/livestream/channels/",
  getParentRoute: () => rootRoute
} as any)

const LivestreamCalendarIndexRoute = LivestreamCalendarIndexImport.update({
  id: "/livestream/calendar/",
  path: "/livestream/calendar/",
  getParentRoute: () => rootRoute
} as any)

const LandingLandingPageIndexRoute = LandingLandingPageIndexImport.update({
  id: "/landing/landing-page/",
  path: "/landing/landing-page/",
  getParentRoute: () => rootRoute
} as any)

const SalesOrdersOrderIdRoute = SalesOrdersOrderIdImport.update({
  id: "/sales/orders/$orderId",
  path: "/sales/orders/$orderId",
  getParentRoute: () => rootRoute
} as any)

const SalesMessagesConversationIdRoute =
  SalesMessagesConversationIdImport.update({
    id: "/sales/messages/$conversationId",
    path: "/sales/messages/$conversationId",
    getParentRoute: () => rootRoute
  } as any)

const SalesItemsItemIdRoute = SalesItemsItemIdImport.update({
  id: "/sales/items/$itemId",
  path: "/sales/items/$itemId",
  getParentRoute: () => rootRoute
} as any)

const SalesFunnelFunnelIdRoute = SalesFunnelFunnelIdImport.update({
  id: "/sales/funnel/$funnelId",
  path: "/sales/funnel/$funnelId",
  getParentRoute: () => rootRoute
} as any)

const SalesDashboardKpiIdRoute = SalesDashboardKpiIdImport.update({
  id: "/sales/dashboard/$kpiId",
  path: "/sales/dashboard/$kpiId",
  getParentRoute: () => rootRoute
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/privacy-policy": {
      id: "/privacy-policy"
      path: "/privacy-policy"
      fullPath: "/privacy-policy"
      preLoaderRoute: typeof PrivacyPolicyImport
      parentRoute: typeof rootRoute
    }
    "/access-denied/": {
      id: "/access-denied/"
      path: "/access-denied"
      fullPath: "/access-denied"
      preLoaderRoute: typeof AccessDeniedIndexImport
      parentRoute: typeof rootRoute
    }
    "/landing/": {
      id: "/landing/"
      path: "/landing"
      fullPath: "/landing"
      preLoaderRoute: typeof LandingIndexImport
      parentRoute: typeof rootRoute
    }
    "/livestream/": {
      id: "/livestream/"
      path: "/livestream"
      fullPath: "/livestream"
      preLoaderRoute: typeof LivestreamIndexImport
      parentRoute: typeof rootRoute
    }
    "/marketing-storage/": {
      id: "/marketing-storage/"
      path: "/marketing-storage"
      fullPath: "/marketing-storage"
      preLoaderRoute: typeof MarketingStorageIndexImport
      parentRoute: typeof rootRoute
    }
    "/postauth/": {
      id: "/postauth/"
      path: "/postauth"
      fullPath: "/postauth"
      preLoaderRoute: typeof PostauthIndexImport
      parentRoute: typeof rootRoute
    }
    "/privacy-policy/": {
      id: "/privacy-policy/"
      path: "/"
      fullPath: "/privacy-policy/"
      preLoaderRoute: typeof PrivacyPolicyIndexImport
      parentRoute: typeof PrivacyPolicyImport
    }
    "/sales/": {
      id: "/sales/"
      path: "/sales"
      fullPath: "/sales"
      preLoaderRoute: typeof SalesIndexImport
      parentRoute: typeof rootRoute
    }
    "/user/": {
      id: "/user/"
      path: "/user"
      fullPath: "/user"
      preLoaderRoute: typeof UserIndexImport
      parentRoute: typeof rootRoute
    }
    "/sales/dashboard/$kpiId": {
      id: "/sales/dashboard/$kpiId"
      path: "/sales/dashboard/$kpiId"
      fullPath: "/sales/dashboard/$kpiId"
      preLoaderRoute: typeof SalesDashboardKpiIdImport
      parentRoute: typeof rootRoute
    }
    "/sales/funnel/$funnelId": {
      id: "/sales/funnel/$funnelId"
      path: "/sales/funnel/$funnelId"
      fullPath: "/sales/funnel/$funnelId"
      preLoaderRoute: typeof SalesFunnelFunnelIdImport
      parentRoute: typeof rootRoute
    }
    "/sales/items/$itemId": {
      id: "/sales/items/$itemId"
      path: "/sales/items/$itemId"
      fullPath: "/sales/items/$itemId"
      preLoaderRoute: typeof SalesItemsItemIdImport
      parentRoute: typeof rootRoute
    }
    "/sales/messages/$conversationId": {
      id: "/sales/messages/$conversationId"
      path: "/sales/messages/$conversationId"
      fullPath: "/sales/messages/$conversationId"
      preLoaderRoute: typeof SalesMessagesConversationIdImport
      parentRoute: typeof rootRoute
    }
    "/sales/orders/$orderId": {
      id: "/sales/orders/$orderId"
      path: "/sales/orders/$orderId"
      fullPath: "/sales/orders/$orderId"
      preLoaderRoute: typeof SalesOrdersOrderIdImport
      parentRoute: typeof rootRoute
    }
    "/landing/landing-page/": {
      id: "/landing/landing-page/"
      path: "/landing/landing-page"
      fullPath: "/landing/landing-page"
      preLoaderRoute: typeof LandingLandingPageIndexImport
      parentRoute: typeof rootRoute
    }
    "/livestream/calendar/": {
      id: "/livestream/calendar/"
      path: "/livestream/calendar"
      fullPath: "/livestream/calendar"
      preLoaderRoute: typeof LivestreamCalendarIndexImport
      parentRoute: typeof rootRoute
    }
    "/livestream/channels/": {
      id: "/livestream/channels/"
      path: "/livestream/channels"
      fullPath: "/livestream/channels"
      preLoaderRoute: typeof LivestreamChannelsIndexImport
      parentRoute: typeof rootRoute
    }
    "/livestream/goals/": {
      id: "/livestream/goals/"
      path: "/livestream/goals"
      fullPath: "/livestream/goals"
      preLoaderRoute: typeof LivestreamGoalsIndexImport
      parentRoute: typeof rootRoute
    }
    "/livestream/members/": {
      id: "/livestream/members/"
      path: "/livestream/members"
      fullPath: "/livestream/members"
      preLoaderRoute: typeof LivestreamMembersIndexImport
      parentRoute: typeof rootRoute
    }
    "/livestream/periods/": {
      id: "/livestream/periods/"
      path: "/livestream/periods"
      fullPath: "/livestream/periods"
      preLoaderRoute: typeof LivestreamPeriodsIndexImport
      parentRoute: typeof rootRoute
    }
    "/livestream/stats/": {
      id: "/livestream/stats/"
      path: "/livestream/stats"
      fullPath: "/livestream/stats"
      preLoaderRoute: typeof LivestreamStatsIndexImport
      parentRoute: typeof rootRoute
    }
    "/marketing-storage/accounting-storage/": {
      id: "/marketing-storage/accounting-storage/"
      path: "/marketing-storage/accounting-storage"
      fullPath: "/marketing-storage/accounting-storage"
      preLoaderRoute: typeof MarketingStorageAccountingStorageIndexImport
      parentRoute: typeof rootRoute
    }
    "/marketing-storage/cal/": {
      id: "/marketing-storage/cal/"
      path: "/marketing-storage/cal"
      fullPath: "/marketing-storage/cal"
      preLoaderRoute: typeof MarketingStorageCalIndexImport
      parentRoute: typeof rootRoute
    }
    "/marketing-storage/calfile/": {
      id: "/marketing-storage/calfile/"
      path: "/marketing-storage/calfile"
      fullPath: "/marketing-storage/calfile"
      preLoaderRoute: typeof MarketingStorageCalfileIndexImport
      parentRoute: typeof rootRoute
    }
    "/marketing-storage/delivered-requests/": {
      id: "/marketing-storage/delivered-requests/"
      path: "/marketing-storage/delivered-requests"
      fullPath: "/marketing-storage/delivered-requests"
      preLoaderRoute: typeof MarketingStorageDeliveredRequestsIndexImport
      parentRoute: typeof rootRoute
    }
    "/marketing-storage/incomes/": {
      id: "/marketing-storage/incomes/"
      path: "/marketing-storage/incomes"
      fullPath: "/marketing-storage/incomes"
      preLoaderRoute: typeof MarketingStorageIncomesIndexImport
      parentRoute: typeof rootRoute
    }
    "/marketing-storage/logs/": {
      id: "/marketing-storage/logs/"
      path: "/marketing-storage/logs"
      fullPath: "/marketing-storage/logs"
      preLoaderRoute: typeof MarketingStorageLogsIndexImport
      parentRoute: typeof rootRoute
    }
    "/marketing-storage/old-logs/": {
      id: "/marketing-storage/old-logs/"
      path: "/marketing-storage/old-logs"
      fullPath: "/marketing-storage/old-logs"
      preLoaderRoute: typeof MarketingStorageOldLogsIndexImport
      parentRoute: typeof rootRoute
    }
    "/marketing-storage/orders-logs/": {
      id: "/marketing-storage/orders-logs/"
      path: "/marketing-storage/orders-logs"
      fullPath: "/marketing-storage/orders-logs"
      preLoaderRoute: typeof MarketingStorageOrdersLogsIndexImport
      parentRoute: typeof rootRoute
    }
    "/marketing-storage/storage/": {
      id: "/marketing-storage/storage/"
      path: "/marketing-storage/storage"
      fullPath: "/marketing-storage/storage"
      preLoaderRoute: typeof MarketingStorageStorageIndexImport
      parentRoute: typeof rootRoute
    }
    "/marketing-storage/system-logs/": {
      id: "/marketing-storage/system-logs/"
      path: "/marketing-storage/system-logs"
      fullPath: "/marketing-storage/system-logs"
      preLoaderRoute: typeof MarketingStorageSystemLogsIndexImport
      parentRoute: typeof rootRoute
    }
    "/marketing-storage/tasks/": {
      id: "/marketing-storage/tasks/"
      path: "/marketing-storage/tasks"
      fullPath: "/marketing-storage/tasks"
      preLoaderRoute: typeof MarketingStorageTasksIndexImport
      parentRoute: typeof rootRoute
    }
    "/sales/channels/": {
      id: "/sales/channels/"
      path: "/sales/channels"
      fullPath: "/sales/channels"
      preLoaderRoute: typeof SalesChannelsIndexImport
      parentRoute: typeof rootRoute
    }
    "/sales/customer-ranks/": {
      id: "/sales/customer-ranks/"
      path: "/sales/customer-ranks"
      fullPath: "/sales/customer-ranks"
      preLoaderRoute: typeof SalesCustomerRanksIndexImport
      parentRoute: typeof rootRoute
    }
    "/sales/daily-reports/": {
      id: "/sales/daily-reports/"
      path: "/sales/daily-reports"
      fullPath: "/sales/daily-reports"
      preLoaderRoute: typeof SalesDailyReportsIndexImport
      parentRoute: typeof rootRoute
    }
    "/sales/dashboard/": {
      id: "/sales/dashboard/"
      path: "/sales/dashboard"
      fullPath: "/sales/dashboard"
      preLoaderRoute: typeof SalesDashboardIndexImport
      parentRoute: typeof rootRoute
    }
    "/sales/funnel/": {
      id: "/sales/funnel/"
      path: "/sales/funnel"
      fullPath: "/sales/funnel"
      preLoaderRoute: typeof SalesFunnelIndexImport
      parentRoute: typeof rootRoute
    }
    "/sales/items/": {
      id: "/sales/items/"
      path: "/sales/items"
      fullPath: "/sales/items"
      preLoaderRoute: typeof SalesItemsIndexImport
      parentRoute: typeof rootRoute
    }
    "/sales/messages/": {
      id: "/sales/messages/"
      path: "/sales/messages"
      fullPath: "/sales/messages"
      preLoaderRoute: typeof SalesMessagesIndexImport
      parentRoute: typeof rootRoute
    }
    "/sales/orders/": {
      id: "/sales/orders/"
      path: "/sales/orders"
      fullPath: "/sales/orders"
      preLoaderRoute: typeof SalesOrdersIndexImport
      parentRoute: typeof rootRoute
    }
    "/sales/price/": {
      id: "/sales/price/"
      path: "/sales/price"
      fullPath: "/sales/price"
      preLoaderRoute: typeof SalesPriceIndexImport
      parentRoute: typeof rootRoute
    }
    "/sales/tasks/": {
      id: "/sales/tasks/"
      path: "/sales/tasks"
      fullPath: "/sales/tasks"
      preLoaderRoute: typeof SalesTasksIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface PrivacyPolicyRouteChildren {
  PrivacyPolicyIndexRoute: typeof PrivacyPolicyIndexRoute
}

const PrivacyPolicyRouteChildren: PrivacyPolicyRouteChildren = {
  PrivacyPolicyIndexRoute: PrivacyPolicyIndexRoute
}

const PrivacyPolicyRouteWithChildren = PrivacyPolicyRoute._addFileChildren(
  PrivacyPolicyRouteChildren
)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/privacy-policy": typeof PrivacyPolicyRouteWithChildren
  "/access-denied": typeof AccessDeniedIndexRoute
  "/landing": typeof LandingIndexRoute
  "/livestream": typeof LivestreamIndexRoute
  "/marketing-storage": typeof MarketingStorageIndexRoute
  "/postauth": typeof PostauthIndexRoute
  "/privacy-policy/": typeof PrivacyPolicyIndexRoute
  "/sales": typeof SalesIndexRoute
  "/user": typeof UserIndexRoute
  "/sales/dashboard/$kpiId": typeof SalesDashboardKpiIdRoute
  "/sales/funnel/$funnelId": typeof SalesFunnelFunnelIdRoute
  "/sales/items/$itemId": typeof SalesItemsItemIdRoute
  "/sales/messages/$conversationId": typeof SalesMessagesConversationIdRoute
  "/sales/orders/$orderId": typeof SalesOrdersOrderIdRoute
  "/landing/landing-page": typeof LandingLandingPageIndexRoute
  "/livestream/calendar": typeof LivestreamCalendarIndexRoute
  "/livestream/channels": typeof LivestreamChannelsIndexRoute
  "/livestream/goals": typeof LivestreamGoalsIndexRoute
  "/livestream/members": typeof LivestreamMembersIndexRoute
  "/livestream/periods": typeof LivestreamPeriodsIndexRoute
  "/livestream/stats": typeof LivestreamStatsIndexRoute
  "/marketing-storage/accounting-storage": typeof MarketingStorageAccountingStorageIndexRoute
  "/marketing-storage/cal": typeof MarketingStorageCalIndexRoute
  "/marketing-storage/calfile": typeof MarketingStorageCalfileIndexRoute
  "/marketing-storage/delivered-requests": typeof MarketingStorageDeliveredRequestsIndexRoute
  "/marketing-storage/incomes": typeof MarketingStorageIncomesIndexRoute
  "/marketing-storage/logs": typeof MarketingStorageLogsIndexRoute
  "/marketing-storage/old-logs": typeof MarketingStorageOldLogsIndexRoute
  "/marketing-storage/orders-logs": typeof MarketingStorageOrdersLogsIndexRoute
  "/marketing-storage/storage": typeof MarketingStorageStorageIndexRoute
  "/marketing-storage/system-logs": typeof MarketingStorageSystemLogsIndexRoute
  "/marketing-storage/tasks": typeof MarketingStorageTasksIndexRoute
  "/sales/channels": typeof SalesChannelsIndexRoute
  "/sales/customer-ranks": typeof SalesCustomerRanksIndexRoute
  "/sales/daily-reports": typeof SalesDailyReportsIndexRoute
  "/sales/dashboard": typeof SalesDashboardIndexRoute
  "/sales/funnel": typeof SalesFunnelIndexRoute
  "/sales/items": typeof SalesItemsIndexRoute
  "/sales/messages": typeof SalesMessagesIndexRoute
  "/sales/orders": typeof SalesOrdersIndexRoute
  "/sales/price": typeof SalesPriceIndexRoute
  "/sales/tasks": typeof SalesTasksIndexRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/access-denied": typeof AccessDeniedIndexRoute
  "/landing": typeof LandingIndexRoute
  "/livestream": typeof LivestreamIndexRoute
  "/marketing-storage": typeof MarketingStorageIndexRoute
  "/postauth": typeof PostauthIndexRoute
  "/privacy-policy": typeof PrivacyPolicyIndexRoute
  "/sales": typeof SalesIndexRoute
  "/user": typeof UserIndexRoute
  "/sales/dashboard/$kpiId": typeof SalesDashboardKpiIdRoute
  "/sales/funnel/$funnelId": typeof SalesFunnelFunnelIdRoute
  "/sales/items/$itemId": typeof SalesItemsItemIdRoute
  "/sales/messages/$conversationId": typeof SalesMessagesConversationIdRoute
  "/sales/orders/$orderId": typeof SalesOrdersOrderIdRoute
  "/landing/landing-page": typeof LandingLandingPageIndexRoute
  "/livestream/calendar": typeof LivestreamCalendarIndexRoute
  "/livestream/channels": typeof LivestreamChannelsIndexRoute
  "/livestream/goals": typeof LivestreamGoalsIndexRoute
  "/livestream/members": typeof LivestreamMembersIndexRoute
  "/livestream/periods": typeof LivestreamPeriodsIndexRoute
  "/livestream/stats": typeof LivestreamStatsIndexRoute
  "/marketing-storage/accounting-storage": typeof MarketingStorageAccountingStorageIndexRoute
  "/marketing-storage/cal": typeof MarketingStorageCalIndexRoute
  "/marketing-storage/calfile": typeof MarketingStorageCalfileIndexRoute
  "/marketing-storage/delivered-requests": typeof MarketingStorageDeliveredRequestsIndexRoute
  "/marketing-storage/incomes": typeof MarketingStorageIncomesIndexRoute
  "/marketing-storage/logs": typeof MarketingStorageLogsIndexRoute
  "/marketing-storage/old-logs": typeof MarketingStorageOldLogsIndexRoute
  "/marketing-storage/orders-logs": typeof MarketingStorageOrdersLogsIndexRoute
  "/marketing-storage/storage": typeof MarketingStorageStorageIndexRoute
  "/marketing-storage/system-logs": typeof MarketingStorageSystemLogsIndexRoute
  "/marketing-storage/tasks": typeof MarketingStorageTasksIndexRoute
  "/sales/channels": typeof SalesChannelsIndexRoute
  "/sales/customer-ranks": typeof SalesCustomerRanksIndexRoute
  "/sales/daily-reports": typeof SalesDailyReportsIndexRoute
  "/sales/dashboard": typeof SalesDashboardIndexRoute
  "/sales/funnel": typeof SalesFunnelIndexRoute
  "/sales/items": typeof SalesItemsIndexRoute
  "/sales/messages": typeof SalesMessagesIndexRoute
  "/sales/orders": typeof SalesOrdersIndexRoute
  "/sales/price": typeof SalesPriceIndexRoute
  "/sales/tasks": typeof SalesTasksIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/privacy-policy": typeof PrivacyPolicyRouteWithChildren
  "/access-denied/": typeof AccessDeniedIndexRoute
  "/landing/": typeof LandingIndexRoute
  "/livestream/": typeof LivestreamIndexRoute
  "/marketing-storage/": typeof MarketingStorageIndexRoute
  "/postauth/": typeof PostauthIndexRoute
  "/privacy-policy/": typeof PrivacyPolicyIndexRoute
  "/sales/": typeof SalesIndexRoute
  "/user/": typeof UserIndexRoute
  "/sales/dashboard/$kpiId": typeof SalesDashboardKpiIdRoute
  "/sales/funnel/$funnelId": typeof SalesFunnelFunnelIdRoute
  "/sales/items/$itemId": typeof SalesItemsItemIdRoute
  "/sales/messages/$conversationId": typeof SalesMessagesConversationIdRoute
  "/sales/orders/$orderId": typeof SalesOrdersOrderIdRoute
  "/landing/landing-page/": typeof LandingLandingPageIndexRoute
  "/livestream/calendar/": typeof LivestreamCalendarIndexRoute
  "/livestream/channels/": typeof LivestreamChannelsIndexRoute
  "/livestream/goals/": typeof LivestreamGoalsIndexRoute
  "/livestream/members/": typeof LivestreamMembersIndexRoute
  "/livestream/periods/": typeof LivestreamPeriodsIndexRoute
  "/livestream/stats/": typeof LivestreamStatsIndexRoute
  "/marketing-storage/accounting-storage/": typeof MarketingStorageAccountingStorageIndexRoute
  "/marketing-storage/cal/": typeof MarketingStorageCalIndexRoute
  "/marketing-storage/calfile/": typeof MarketingStorageCalfileIndexRoute
  "/marketing-storage/delivered-requests/": typeof MarketingStorageDeliveredRequestsIndexRoute
  "/marketing-storage/incomes/": typeof MarketingStorageIncomesIndexRoute
  "/marketing-storage/logs/": typeof MarketingStorageLogsIndexRoute
  "/marketing-storage/old-logs/": typeof MarketingStorageOldLogsIndexRoute
  "/marketing-storage/orders-logs/": typeof MarketingStorageOrdersLogsIndexRoute
  "/marketing-storage/storage/": typeof MarketingStorageStorageIndexRoute
  "/marketing-storage/system-logs/": typeof MarketingStorageSystemLogsIndexRoute
  "/marketing-storage/tasks/": typeof MarketingStorageTasksIndexRoute
  "/sales/channels/": typeof SalesChannelsIndexRoute
  "/sales/customer-ranks/": typeof SalesCustomerRanksIndexRoute
  "/sales/daily-reports/": typeof SalesDailyReportsIndexRoute
  "/sales/dashboard/": typeof SalesDashboardIndexRoute
  "/sales/funnel/": typeof SalesFunnelIndexRoute
  "/sales/items/": typeof SalesItemsIndexRoute
  "/sales/messages/": typeof SalesMessagesIndexRoute
  "/sales/orders/": typeof SalesOrdersIndexRoute
  "/sales/price/": typeof SalesPriceIndexRoute
  "/sales/tasks/": typeof SalesTasksIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/privacy-policy"
    | "/access-denied"
    | "/landing"
    | "/livestream"
    | "/marketing-storage"
    | "/postauth"
    | "/privacy-policy/"
    | "/sales"
    | "/user"
    | "/sales/dashboard/$kpiId"
    | "/sales/funnel/$funnelId"
    | "/sales/items/$itemId"
    | "/sales/messages/$conversationId"
    | "/sales/orders/$orderId"
    | "/landing/landing-page"
    | "/livestream/calendar"
    | "/livestream/channels"
    | "/livestream/goals"
    | "/livestream/members"
    | "/livestream/periods"
    | "/livestream/stats"
    | "/marketing-storage/accounting-storage"
    | "/marketing-storage/cal"
    | "/marketing-storage/calfile"
    | "/marketing-storage/delivered-requests"
    | "/marketing-storage/incomes"
    | "/marketing-storage/logs"
    | "/marketing-storage/old-logs"
    | "/marketing-storage/orders-logs"
    | "/marketing-storage/storage"
    | "/marketing-storage/system-logs"
    | "/marketing-storage/tasks"
    | "/sales/channels"
    | "/sales/customer-ranks"
    | "/sales/daily-reports"
    | "/sales/dashboard"
    | "/sales/funnel"
    | "/sales/items"
    | "/sales/messages"
    | "/sales/orders"
    | "/sales/price"
    | "/sales/tasks"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/access-denied"
    | "/landing"
    | "/livestream"
    | "/marketing-storage"
    | "/postauth"
    | "/privacy-policy"
    | "/sales"
    | "/user"
    | "/sales/dashboard/$kpiId"
    | "/sales/funnel/$funnelId"
    | "/sales/items/$itemId"
    | "/sales/messages/$conversationId"
    | "/sales/orders/$orderId"
    | "/landing/landing-page"
    | "/livestream/calendar"
    | "/livestream/channels"
    | "/livestream/goals"
    | "/livestream/members"
    | "/livestream/periods"
    | "/livestream/stats"
    | "/marketing-storage/accounting-storage"
    | "/marketing-storage/cal"
    | "/marketing-storage/calfile"
    | "/marketing-storage/delivered-requests"
    | "/marketing-storage/incomes"
    | "/marketing-storage/logs"
    | "/marketing-storage/old-logs"
    | "/marketing-storage/orders-logs"
    | "/marketing-storage/storage"
    | "/marketing-storage/system-logs"
    | "/marketing-storage/tasks"
    | "/sales/channels"
    | "/sales/customer-ranks"
    | "/sales/daily-reports"
    | "/sales/dashboard"
    | "/sales/funnel"
    | "/sales/items"
    | "/sales/messages"
    | "/sales/orders"
    | "/sales/price"
    | "/sales/tasks"
  id:
    | "__root__"
    | "/"
    | "/privacy-policy"
    | "/access-denied/"
    | "/landing/"
    | "/livestream/"
    | "/marketing-storage/"
    | "/postauth/"
    | "/privacy-policy/"
    | "/sales/"
    | "/user/"
    | "/sales/dashboard/$kpiId"
    | "/sales/funnel/$funnelId"
    | "/sales/items/$itemId"
    | "/sales/messages/$conversationId"
    | "/sales/orders/$orderId"
    | "/landing/landing-page/"
    | "/livestream/calendar/"
    | "/livestream/channels/"
    | "/livestream/goals/"
    | "/livestream/members/"
    | "/livestream/periods/"
    | "/livestream/stats/"
    | "/marketing-storage/accounting-storage/"
    | "/marketing-storage/cal/"
    | "/marketing-storage/calfile/"
    | "/marketing-storage/delivered-requests/"
    | "/marketing-storage/incomes/"
    | "/marketing-storage/logs/"
    | "/marketing-storage/old-logs/"
    | "/marketing-storage/orders-logs/"
    | "/marketing-storage/storage/"
    | "/marketing-storage/system-logs/"
    | "/marketing-storage/tasks/"
    | "/sales/channels/"
    | "/sales/customer-ranks/"
    | "/sales/daily-reports/"
    | "/sales/dashboard/"
    | "/sales/funnel/"
    | "/sales/items/"
    | "/sales/messages/"
    | "/sales/orders/"
    | "/sales/price/"
    | "/sales/tasks/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRouteWithChildren
  AccessDeniedIndexRoute: typeof AccessDeniedIndexRoute
  LandingIndexRoute: typeof LandingIndexRoute
  LivestreamIndexRoute: typeof LivestreamIndexRoute
  MarketingStorageIndexRoute: typeof MarketingStorageIndexRoute
  PostauthIndexRoute: typeof PostauthIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  UserIndexRoute: typeof UserIndexRoute
  SalesDashboardKpiIdRoute: typeof SalesDashboardKpiIdRoute
  SalesFunnelFunnelIdRoute: typeof SalesFunnelFunnelIdRoute
  SalesItemsItemIdRoute: typeof SalesItemsItemIdRoute
  SalesMessagesConversationIdRoute: typeof SalesMessagesConversationIdRoute
  SalesOrdersOrderIdRoute: typeof SalesOrdersOrderIdRoute
  LandingLandingPageIndexRoute: typeof LandingLandingPageIndexRoute
  LivestreamCalendarIndexRoute: typeof LivestreamCalendarIndexRoute
  LivestreamChannelsIndexRoute: typeof LivestreamChannelsIndexRoute
  LivestreamGoalsIndexRoute: typeof LivestreamGoalsIndexRoute
  LivestreamMembersIndexRoute: typeof LivestreamMembersIndexRoute
  LivestreamPeriodsIndexRoute: typeof LivestreamPeriodsIndexRoute
  LivestreamStatsIndexRoute: typeof LivestreamStatsIndexRoute
  MarketingStorageAccountingStorageIndexRoute: typeof MarketingStorageAccountingStorageIndexRoute
  MarketingStorageCalIndexRoute: typeof MarketingStorageCalIndexRoute
  MarketingStorageCalfileIndexRoute: typeof MarketingStorageCalfileIndexRoute
  MarketingStorageDeliveredRequestsIndexRoute: typeof MarketingStorageDeliveredRequestsIndexRoute
  MarketingStorageIncomesIndexRoute: typeof MarketingStorageIncomesIndexRoute
  MarketingStorageLogsIndexRoute: typeof MarketingStorageLogsIndexRoute
  MarketingStorageOldLogsIndexRoute: typeof MarketingStorageOldLogsIndexRoute
  MarketingStorageOrdersLogsIndexRoute: typeof MarketingStorageOrdersLogsIndexRoute
  MarketingStorageStorageIndexRoute: typeof MarketingStorageStorageIndexRoute
  MarketingStorageSystemLogsIndexRoute: typeof MarketingStorageSystemLogsIndexRoute
  MarketingStorageTasksIndexRoute: typeof MarketingStorageTasksIndexRoute
  SalesChannelsIndexRoute: typeof SalesChannelsIndexRoute
  SalesCustomerRanksIndexRoute: typeof SalesCustomerRanksIndexRoute
  SalesDailyReportsIndexRoute: typeof SalesDailyReportsIndexRoute
  SalesDashboardIndexRoute: typeof SalesDashboardIndexRoute
  SalesFunnelIndexRoute: typeof SalesFunnelIndexRoute
  SalesItemsIndexRoute: typeof SalesItemsIndexRoute
  SalesMessagesIndexRoute: typeof SalesMessagesIndexRoute
  SalesOrdersIndexRoute: typeof SalesOrdersIndexRoute
  SalesPriceIndexRoute: typeof SalesPriceIndexRoute
  SalesTasksIndexRoute: typeof SalesTasksIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRouteWithChildren,
  AccessDeniedIndexRoute: AccessDeniedIndexRoute,
  LandingIndexRoute: LandingIndexRoute,
  LivestreamIndexRoute: LivestreamIndexRoute,
  MarketingStorageIndexRoute: MarketingStorageIndexRoute,
  PostauthIndexRoute: PostauthIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  UserIndexRoute: UserIndexRoute,
  SalesDashboardKpiIdRoute: SalesDashboardKpiIdRoute,
  SalesFunnelFunnelIdRoute: SalesFunnelFunnelIdRoute,
  SalesItemsItemIdRoute: SalesItemsItemIdRoute,
  SalesMessagesConversationIdRoute: SalesMessagesConversationIdRoute,
  SalesOrdersOrderIdRoute: SalesOrdersOrderIdRoute,
  LandingLandingPageIndexRoute: LandingLandingPageIndexRoute,
  LivestreamCalendarIndexRoute: LivestreamCalendarIndexRoute,
  LivestreamChannelsIndexRoute: LivestreamChannelsIndexRoute,
  LivestreamGoalsIndexRoute: LivestreamGoalsIndexRoute,
  LivestreamMembersIndexRoute: LivestreamMembersIndexRoute,
  LivestreamPeriodsIndexRoute: LivestreamPeriodsIndexRoute,
  LivestreamStatsIndexRoute: LivestreamStatsIndexRoute,
  MarketingStorageAccountingStorageIndexRoute:
    MarketingStorageAccountingStorageIndexRoute,
  MarketingStorageCalIndexRoute: MarketingStorageCalIndexRoute,
  MarketingStorageCalfileIndexRoute: MarketingStorageCalfileIndexRoute,
  MarketingStorageDeliveredRequestsIndexRoute:
    MarketingStorageDeliveredRequestsIndexRoute,
  MarketingStorageIncomesIndexRoute: MarketingStorageIncomesIndexRoute,
  MarketingStorageLogsIndexRoute: MarketingStorageLogsIndexRoute,
  MarketingStorageOldLogsIndexRoute: MarketingStorageOldLogsIndexRoute,
  MarketingStorageOrdersLogsIndexRoute: MarketingStorageOrdersLogsIndexRoute,
  MarketingStorageStorageIndexRoute: MarketingStorageStorageIndexRoute,
  MarketingStorageSystemLogsIndexRoute: MarketingStorageSystemLogsIndexRoute,
  MarketingStorageTasksIndexRoute: MarketingStorageTasksIndexRoute,
  SalesChannelsIndexRoute: SalesChannelsIndexRoute,
  SalesCustomerRanksIndexRoute: SalesCustomerRanksIndexRoute,
  SalesDailyReportsIndexRoute: SalesDailyReportsIndexRoute,
  SalesDashboardIndexRoute: SalesDashboardIndexRoute,
  SalesFunnelIndexRoute: SalesFunnelIndexRoute,
  SalesItemsIndexRoute: SalesItemsIndexRoute,
  SalesMessagesIndexRoute: SalesMessagesIndexRoute,
  SalesOrdersIndexRoute: SalesOrdersIndexRoute,
  SalesPriceIndexRoute: SalesPriceIndexRoute,
  SalesTasksIndexRoute: SalesTasksIndexRoute
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/privacy-policy",
        "/access-denied/",
        "/landing/",
        "/livestream/",
        "/marketing-storage/",
        "/postauth/",
        "/sales/",
        "/user/",
        "/sales/dashboard/$kpiId",
        "/sales/funnel/$funnelId",
        "/sales/items/$itemId",
        "/sales/messages/$conversationId",
        "/sales/orders/$orderId",
        "/landing/landing-page/",
        "/livestream/calendar/",
        "/livestream/channels/",
        "/livestream/goals/",
        "/livestream/members/",
        "/livestream/periods/",
        "/livestream/stats/",
        "/marketing-storage/accounting-storage/",
        "/marketing-storage/cal/",
        "/marketing-storage/calfile/",
        "/marketing-storage/delivered-requests/",
        "/marketing-storage/incomes/",
        "/marketing-storage/logs/",
        "/marketing-storage/old-logs/",
        "/marketing-storage/orders-logs/",
        "/marketing-storage/storage/",
        "/marketing-storage/system-logs/",
        "/marketing-storage/tasks/",
        "/sales/channels/",
        "/sales/customer-ranks/",
        "/sales/daily-reports/",
        "/sales/dashboard/",
        "/sales/funnel/",
        "/sales/items/",
        "/sales/messages/",
        "/sales/orders/",
        "/sales/price/",
        "/sales/tasks/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/privacy-policy": {
      "filePath": "privacy-policy.tsx",
      "children": [
        "/privacy-policy/"
      ]
    },
    "/access-denied/": {
      "filePath": "access-denied/index.tsx"
    },
    "/landing/": {
      "filePath": "landing/index.tsx"
    },
    "/livestream/": {
      "filePath": "livestream/index.tsx"
    },
    "/marketing-storage/": {
      "filePath": "marketing-storage/index.tsx"
    },
    "/postauth/": {
      "filePath": "postauth/index.tsx"
    },
    "/privacy-policy/": {
      "filePath": "privacy-policy/index.tsx",
      "parent": "/privacy-policy"
    },
    "/sales/": {
      "filePath": "sales/index.tsx"
    },
    "/user/": {
      "filePath": "user/index.tsx"
    },
    "/sales/dashboard/$kpiId": {
      "filePath": "sales/dashboard/$kpiId.tsx"
    },
    "/sales/funnel/$funnelId": {
      "filePath": "sales/funnel/$funnelId.tsx"
    },
    "/sales/items/$itemId": {
      "filePath": "sales/items/$itemId.tsx"
    },
    "/sales/messages/$conversationId": {
      "filePath": "sales/messages/$conversationId.tsx"
    },
    "/sales/orders/$orderId": {
      "filePath": "sales/orders/$orderId.tsx"
    },
    "/landing/landing-page/": {
      "filePath": "landing/landing-page/index.tsx"
    },
    "/livestream/calendar/": {
      "filePath": "livestream/calendar/index.tsx"
    },
    "/livestream/channels/": {
      "filePath": "livestream/channels/index.tsx"
    },
    "/livestream/goals/": {
      "filePath": "livestream/goals/index.tsx"
    },
    "/livestream/members/": {
      "filePath": "livestream/members/index.tsx"
    },
    "/livestream/periods/": {
      "filePath": "livestream/periods/index.tsx"
    },
    "/livestream/stats/": {
      "filePath": "livestream/stats/index.tsx"
    },
    "/marketing-storage/accounting-storage/": {
      "filePath": "marketing-storage/accounting-storage/index.tsx"
    },
    "/marketing-storage/cal/": {
      "filePath": "marketing-storage/cal/index.tsx"
    },
    "/marketing-storage/calfile/": {
      "filePath": "marketing-storage/calfile/index.tsx"
    },
    "/marketing-storage/delivered-requests/": {
      "filePath": "marketing-storage/delivered-requests/index.tsx"
    },
    "/marketing-storage/incomes/": {
      "filePath": "marketing-storage/incomes/index.tsx"
    },
    "/marketing-storage/logs/": {
      "filePath": "marketing-storage/logs/index.tsx"
    },
    "/marketing-storage/old-logs/": {
      "filePath": "marketing-storage/old-logs/index.tsx"
    },
    "/marketing-storage/orders-logs/": {
      "filePath": "marketing-storage/orders-logs/index.tsx"
    },
    "/marketing-storage/storage/": {
      "filePath": "marketing-storage/storage/index.tsx"
    },
    "/marketing-storage/system-logs/": {
      "filePath": "marketing-storage/system-logs/index.tsx"
    },
    "/marketing-storage/tasks/": {
      "filePath": "marketing-storage/tasks/index.tsx"
    },
    "/sales/channels/": {
      "filePath": "sales/channels/index.tsx"
    },
    "/sales/customer-ranks/": {
      "filePath": "sales/customer-ranks/index.tsx"
    },
    "/sales/daily-reports/": {
      "filePath": "sales/daily-reports/index.tsx"
    },
    "/sales/dashboard/": {
      "filePath": "sales/dashboard/index.tsx"
    },
    "/sales/funnel/": {
      "filePath": "sales/funnel/index.tsx"
    },
    "/sales/items/": {
      "filePath": "sales/items/index.tsx"
    },
    "/sales/messages/": {
      "filePath": "sales/messages/index.tsx"
    },
    "/sales/orders/": {
      "filePath": "sales/orders/index.tsx"
    },
    "/sales/price/": {
      "filePath": "sales/price/index.tsx"
    },
    "/sales/tasks/": {
      "filePath": "sales/tasks/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
